/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.gradle;

import java.util.HashMap;
import java.util.Map;

import org.json.JSONObject;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public JSONObject createJSONObject(Map<String, String> data) {
        return new JSONObject(data);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Map<String,String> map = new HashMap<String,String>() {
            {
               put("key1", "value1");
               put("key2", "value2");
            }
           };
        System.out.println(new App().createJSONObject(map));
    }
}
